# Generated by Django 3.2 on 2025-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
