# Generated by Django 3.2 on 2025-05-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.IntegerField(help_text='Giá của thuốc (đơn vị: VND)')),
                ('stock', models.IntegerField(default=0, help_text='Số lượng thuốc còn trong kho (tồn kho)')),
                ('description_html', models.TextField(blank=True, help_text='Mô tả HTML chi tiết thuốc')),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.CharField(help_text='ID cuộc hẹn', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ bán thuốc'), ('sold', 'Đã bán xong'), ('partial', 'Bán một phần')], default='pending', help_text='Trạng thái đơn thuốc', max_length=50)),
                ('totals', models.IntegerField(help_text='Tổng tiền đơn thuốc (VND)')),
                ('image', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, help_text='Ngày tạo đơn thuốc')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(help_text='Giá thuốc tại thời điểm kê đơn')),
                ('quantity', models.PositiveIntegerField(help_text='Số lượng thuốc trong đơn')),
                ('status', models.CharField(choices=[('pending', 'Chưa bán'), ('sold', 'Đã bán')], default='pending', help_text='Trạng thái bán thuốc', max_length=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'prescription_medicines',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cashier_id', models.CharField(max_length=50)),
                ('totals', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo hóa đơn')),
                ('prescription', models.ForeignKey(help_text='Đơn thuốc được thanh toán', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
