# Generated by Django 3.2 on 2025-05-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_prescriptionmedicine_directions_for_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='appointment_id',
            new_name='medical_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='totals',
        ),
    ]
