# Generated by Django 3.2 on 2025-05-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_invoice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='cashier_id',
            new_name='pharmacist_id',
        ),
    ]
