# Generated by Django 3.2 on 2025-05-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_rename_cashier_id_invoice_pharmacist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
