# Generated by Django 5.2 on 2025-04-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='user_id',
            new_name='user',
        ),
    ]
