# Generated by Django 5.2 on 2025-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_id_doctor_user_rename_user_id_nurse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='technician',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='technician',
            name='image',
            field=models.TextField(),
        ),
    ]
