# Generated by Django 3.2 on 2025-05-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
