# Generated by Django 3.2 on 2025-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicine_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='directions_for_use',
            field=models.TextField(blank=True, null=True),
        ),
    ]
